name: website

on:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install
        if: success()
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Yarn Build
        if: success()
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
